name: Direct Merge Patch to Minor

on:
  pull_request:
    types:
      - closed
    branches:
      - patch

jobs:
  direct-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "RobAndrewHurst"
          git config user.email "robert.hurst@geolytix.co.uk"
          git remote set-url origin "https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

      - name: Merge patch into minor
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Fetching branches..."
          git fetch origin
          
          echo "Checking out minor branch..."
          git checkout minor
          git pull origin minor
          
          echo "Attempting merge..."
          if git merge origin/patch --no-edit; then
            echo "Merge successful, pushing changes..."
            git push "https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" minor
            echo "Successfully merged patch into minor"
          else
            echo "Merge conflicts detected. Manual intervention required."
            exit 1
          fi