name: Direct Merge Patch to Minor

on:
  pull_request:
    types:
      - closed
    branches:
      - patch

jobs:
  direct-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        env:
            PAT_TOKEN: ${{secrets.PAT_TOKEN}}
        with:
          fetch-depth: 0
          # Use a personal access token with necessary permissions to bypass branch restrictions
          token: PAT_TOKEN

      - name: Configure Git
        env:
            TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
            git config user.name "GitHub Actions Bot"
            git config user.email "actions@github.com"
            git config --global url."https://$TOKEN@github.com/".insteadOf "https://github.com/"

      - name: Merge patch into minor
        run: |
            echo "Fetching branches..."
            git fetch origin
        
            echo "Checking out minor branch..."
            git checkout minor
            git pull origin minor
            
            echo "Attempting merge..."
            if git merge origin/patch --no-edit; then
                echo "Merge successful, pushing changes..."
                git push origin minor
                echo "Successfully merged patch into minor"
            else
                echo "Merge conflicts detected. Manual intervention required."
                exit 1
            fi