name: patch-merge 
on:
    pull_request:
      types:
        - closed
      branches:
        - patch

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge patch -> minor
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: minor
          message: Merge patch into minor
          github_token: ${{ secrets.PAT_TOKEN }}